### ISSUE TITLE
Inconsistent with MapPLUTO

### ISSUE THREAD

**Issue by LINCH8** [CityOfNewYork/nyc-planimetrics#10]
I am trying to intersect the Footprints map with MapPLUTO. But it appears that the polygons in these two datasets are not perfectly consistent: for many buildings, a small proportion of them are outside the corresponding tax lots. Is this a known issue? And is there a method to deal with this?

**Comment by mattyschell** [comment]
Hello @LINCH8 thanks for your interest!

Yes, this is a known issue.  The tax lots in NYC were digitized long ago from paper sources so you will see tax lots that are usually topologicially accurate but strictly accurate relative to other data sources.

Generally the data we release from planimetrics is accurate and should align well with other accurate sources like orthophotos and open street map.  If you see any exceptions please let us know.
