### ISSUE TITLE
How was this dataset created?

### ISSUE THREAD

**Issue by EdwardDeaver** [CityOfNewYork/nyc-planimetrics#11]
Hi, 

I'm trying to understand how this dataset was made? I would be interested in applying that methodology to other cities especially with now available high-resolution aerial data from Google Maps. 

Thank you for your time.

**Comment by mattyschell** [comment]
@EdwardDeaver thanks for your interest!  I'm not sure if you're still out there but I am here, resurrecting this repository and your issue filed 7 months ago.

Great question.   The primary input to the planimetric data creation is orthophotography captured under a joint project of New York State and New York City.  These orthophotos are released to the public.  Much of the tricky work leading up to this dataset is contracting and legal agreements.

If you are thinking about using imagery from some other source like google maps you'll want to read their terms of service.  I can't speak to whether your use case is allowed under Google's terms of service.  Good luck! 

I'm gonna close this just to tidy up the issues list but feel free to start up a new issue if you like.
