### ISSUE TITLE
Decide how to manage subtypes and attribute domains in shapefiles

### ISSUE THREAD

**Issue by mattyschell** [CityOfNewYork/nyc-planimetrics#16]
Planimetrics data must be provided to NYC Open Data as shapefiles.  Shapefiles do not support subtypes and attribute domains.

We'll need to decide what to do.  And the documentation in this repository will need to reflect that.

**Comment by mattyschell** [comment]
Pfitts says

> •	Regarding Subtypes/Domains, that is a fair point. Since non-Esri client applications and Shapefiles don’t recognize them, often I use human readable coded values that matches the description which covers situations like this. If needed using FME or some other tool, we can likely add a new field that writes the domain or subtype description instead of the integer value, if that can be determined from the Planimetric geodatabase. Without seeing the data hard to make a definitive decision, but this is an age-old challenge!

**Comment by mrahman-doitt** [comment]
Based on current Planimetrics data on Open data portal, the Subtypes/Domains were not resolved in the Shapefiles before publishing.

**Comment by mattyschell** [comment]
We will continue to publish the dastardly codes in the NYC open data shapefiles.  The open data data datasets are truncated and replaced wherever possible.  A user looking for "boardwalks," for example, will always find the latest boardwalks. We don't want to redefine column names, data types, and lengths unless absolutely necessary.
