### ISSUE TITLE
housekeeping - tags and branches

### ISSUE THREAD

**Issue by mattyschell** [CityOfNewYork/nyc-planimetrics#17]
Get organized for the 2022 updates.

1. Create a branch called next
2. Fork next for all work
3. Add a tag planimetrics_2014 
4. Use the planimetrics_2014 tag permalink in the documentation.  It should say something like "looking for older capture rules - planimetrics_2014 (url here)"

**Comment by jwileman1** [comment]
sounds good

**Comment by mattyschell** [comment]
1.  tagged v.2014 as planimetrics-2014
2. created branch next from main
3. created branch throwaway from main

**Comment by mattyschell** [comment]
@jwileman1 here's the permalink for the 2014 tag.  

https://github.com/CityOfNewYork/nyc-planimetrics/tree/planimetrics-2014

We'll want whatever you cook up to be the default planimetrics metadata landing page.  But near the top we propose a link like

> Looking for older capture rules? See the [2014 rules here](https://github.com/CityOfNewYork/nyc-planimetrics/tree/planimetrics-2014)

**Comment by jwileman1** [comment]
Hey Matt-  Hope you are feeling better.  You want me to make edits to 'next' branch?  Go a couple minutes to talk ?
Thanks, John
________________________________

**Comment by mattyschell** [comment]
Calling this one closed, thanks @jwileman1
