### ISSUE TITLE
Decide what to do with "comments" and other working columns

### ISSUE THREAD

**Issue by mattyschell** [CityOfNewYork/nyc-planimetrics#20]
The planimetrics 2022 delivery includes several columns that probably shouldn't be published.  This gets confusing because in most cases we are saying that the delivered data is gospel even if it doesn't match the capture rules.

If we decide not to publish columns like "comments" we'll need to revise the planimetrics 2022 documentation in this repository.

**Comment by jwileman1** [comment]
note: only building footprint had a Comments column ... not saying that there aren't others (with different names)  ... just saying building footprint had a Comments
