### ISSUE TITLE
Numeric feature codes

### ISSUE THREAD

**Issue by jwileman1** [CityOfNewYork/nyc-planimetrics#21]
Are the numeric feature_codes used elsewhere (just checked a couple feature classes so far - but seems they are not used in file gdb)?  ex: Building_footprint// Skybridge = 2110

If not, probably ought to remove from metadata ... just don't want to start removing 'good' info with checking ... 

Looks like here is what exists:
Fior example in the feature class called BUILDING_FOOTPRINT.  The FEATURE_CLASS and SUB_FEATURE_CODE are both the subtype name ( numeric code not used in either). Ex: FEATURE_CLASS = Building  ... and SUB_FEATURE_CODE = Building 

In the metadata, there are subtype names and codes:

Subtype	                                     Feature Code
Building	                                     2100
Sky Bridge	                             2110
Building Under Construction	     5100
Garage	                                     5110

I can 'clean' this up by removing numeric codes but wanted to double check first.  Remove numeric codes?

**Comment by mattyschell** [comment]
Good question.  According to @mrahman-doitt over on issue #16 the subtypes/domains have not typically been resolved when we publish as shapefiles on the NYC open data site.  

Similar to length > 10 column names, we need to indicate both the codes and the names in the documentation here.

**Comment by jwileman1** [comment]
OK, sounds good ... I will keep the numeric codes in metadata ... understood.

where can I find a list of codes?  so, far I need the code for cantilevered building subtype within building footprint feature class

pretty sure there will be others ... so, can just request them here ?

**Comment by mattyschell** [comment]
We maintain and publish building footprints separately from this planimetrics point-in-time collection so for buildings you should find everything [here](https://github.com/CityOfNewYork/nyc-geo-metadata/blob/main/Metadata/Metadata_BuildingFootprints.md)

> 1006 = Cantilevered Building

Sure, I'll be happy to find any others, drop them here.  Is there a way to find these in the file geodatabase?   I know it's possible in enterprise geodatabases to review domains and subtypes in the ArcCatalog GUI.

**Comment by jwileman1** [comment]
thanks for cant. bldg code- i added it to metadata ...

I don't see the numeric codes anywhere in the file gdb ... but that link you provided should do the trick- thanks

**Comment by jwileman1** [comment]
i cannot fide codes for medians in that link ... please advise:

median- traffic island
median - other 

also, regarding median-other ... this subtype is not in the capture rules document.  There are 15 features in the planimetric data. 
 so, I'll create a template in the metadata but will (please) need help filling it out later. Will also need Feature View.

**Comment by mattyschell** [comment]
Sure thing.  

360070 = Other (median)
360080 = Median Traffic Island

I pulled those from the domains viewer in ArcGIS Pro

![image](https://github.com/CityOfNewYork/nyc-planimetrics/assets/3792238/98cd1ce5-cf8b-4798-ba46-0a61c0810bf5)

**Comment by mattyschell** [comment]
> I'll create a template in the metadata but will (please) need help filling it out later. Will also need Feature View

Got it, thanks.  I updated issue #24 to be more generic so we can keep a running list of missing feature views.  Thanks for pointing these out.

**Comment by jwileman1** [comment]
It has been a bit since working with file gdb ... thanks for refresher- i see the domains now ... apologies.
