### ISSUE TITLE
Building_footprint notes- fyi

### ISSUE THREAD

**Issue by jwileman1** [CityOfNewYork/nyc-planimetrics#22]
Building_footprint notes- fyi (not an issue ... just so you know)

2022 Capture Rules 'requested' these Building footprint subtypes be captured but they are not in planimetric data.  They were all listed as "New domain value":

GAS_STATION_CANOPY
STORAGE_TANK
PARKING
AUXILIARY_STRUCTURE

TEMPORARY_STRUCTURE

Note :  CANTILEVERED_BUILDING was also a new domain value, but it was captured in the planimetric data

just so you know ...

**Comment by mattyschell** [comment]
Thanks!  Yes, this was one of the verbal agreements made between the vendor and agency management.  

We should not document those 5 "new" domain values that were not collected.
