### ISSUE TITLE
Misc Issues/Comments

### ISSUE THREAD

**Issue by jwileman1** [CityOfNewYork/nyc-planimetrics#26]
1.) Within ground elevation for Buildings ...  "A bare-earth surface is generated from the 2010 LiDAR by first removing any points that fall within a building polygon" ...  Is 2010 still correct? 

2.) Don't forget to update the URL to 2022 file gdb.  "Previous Capture" table needs to be updated with this download URL ... when ready to publish ... 

3.) These feature classes exist in file gdb, but I did not include in metadata because I think NYC does not publish these ... just making sure:
	-Deleted_line
	-Deleted_point
	-Deleted_polygon
	-NYCPlanimetric_Topology
	-Updated_line
	-Updated_point
	-Updated_polygon
4.) These feature classes exist in file gdb and were newly added to metadata:
      -Curb Cut
      -Pavement Edge carto
      -Street Centerline
      -Water Tank

**Comment by mattyschell** [comment]
> 1.) Within ground elevation for Buildings ... "A bare-earth surface is generated from the 2010 LiDAR by first removing any points that fall within a building polygon" ... Is 2010 still correct?

I am going to replace this section of text with the latest capture rules text.  Since this is unpublished data I dont think it is critical.

**Comment by mattyschell** [comment]
> 2.) Don't forget to update the URL to 2022 file gdb. "Previous Capture" table needs to be updated with this download URL ... when ready to publish ...

Let's move this to a separate issue

**Comment by mattyschell** [comment]
> 3.) These feature classes exist in file gdb, but I did not include in metadata because I think NYC does not publish these ... just making sure:
-Deleted_line
-Deleted_point
-Deleted_polygon
-NYCPlanimetric_Topology
-Updated_line
-Updated_point
-Updated_polygon

Verified!

**Comment by mattyschell** [comment]
> 4.) These feature classes exist in file gdb and were newly added to metadata:
-Curb Cut
-Pavement Edge carto
-Street Centerline
-Water Tank

Verified.  Except street_centerline which we decided not to publish

**Comment by mattyschell** [comment]
closed in https://github.com/CityOfNewYork/nyc-planimetrics/pull/33
