### ISSUE TITLE
Potential Source of Confusion - Park Boundary along Parkways

### ISSUE THREAD

**Issue by mtreg** [CityOfNewYork/nyc-planimetrics#7]
Flagging this as a potential source of confusion: 
Parkways in NYC (e.g., Belt Parkway in Brooklyn/Queens and Korean War Vets Parkway in Staten Island) are listed in the NYC DPR Properties Layer, though they don't really provide access to people. Thus, while medians and boundary vegetation along these roads are designated in the Park/Open Space dataset as "Park Boundary," it might be helpful to define this intricacy somewhere. Or perhaps categorize Accessible vs In-Accessible Open Space/Park Land, which would be more broadly useful. 

Holler with any questions on this! Thanks!
mike treglia

**Comment by colinreilly** [comment]
@mtreg This should be brought up with NYC Parks. NYC Parks categorizes these as greenways. I agree though that this is an odd distinction as these are really not parks.
